// Built-in providers register themselves on import. Add new providers below (one line each).
import './smtp'
import './webhook'
import './discord'
import './slack'
import './telegram'
import './teams'
import './ntfy'
import './gotify'
import './pushover'
import './matrix'
// Wave 2
import './mattermost'
import './rocket-chat'
import './google-chat'
import './pagerduty'
import './opsgenie'
import './apprise'
import './signal'
import './home-assistant'
import './pushbullet'
import './twilio'
import './sendgrid'
import './resend'
import './bark'
import './pushdeer'
import './serverchan'
import './splunk'
import './squadcast'
import './webpush'
import './line-messaging'
import './pumble'
import './zoho-cliq'
import './clicksend'
import './alerta'
import './grafana-oncall'
import './heii-oncall'
import './nextcloud-talk'
import './techulus-push'
import './pushy'
import './onebot'
import './wecom'
import './dingding'
import './feishu'
import './bitrix24'

export * from './describe'
export * from './http'
export * from './registry'
export * from './types'
