import { z } from 'zod'

import { SSO_DOMAINS_SLUG } from '@/collections/SsoDomains'
import type { SsoDomain } from '@/payload-types'
import {
  errorMessage,
  errorStatus,
  jsonError,
  readJson,
  resolveOrgRequest,
} from '@/server/notifications/api'
import { toDomainRow } from '@/server/sso/domain-rows'
import { errorText } from '@/server/request-locale'

export const dynamic = 'force-dynamic'

type RouteContext = { params: Promise<{ orgId: string }> }

const createSchema = z.object({ domain: z.string().trim().min(3).max(253) })

/** GET /api/orgs/:orgId/sso/domains — the organization's domains with their DNS records (`sso:read`). */
export async function GET(request: Request, { params }: RouteContext) {
  const { orgId } = await params
  const ctx = await resolveOrgRequest(request, orgId, 'sso:read')
  if (ctx instanceof Response) return ctx

  const { docs } = await ctx.payload.find({
    collection: SSO_DOMAINS_SLUG,
    where: { organization: { equals: ctx.orgId } },
    sort: 'domain',
    depth: 0,
    limit: 100,
    user: ctx.user,
    overrideAccess: false,
  })
  return Response.json({ docs: (docs as SsoDomain[]).map(toDomainRow) })
}

/** POST /api/orgs/:orgId/sso/domains `{ domain }` — add a domain to verify (`sso:manage`). */
export async function POST(request: Request, { params }: RouteContext) {
  const { orgId } = await params
  const ctx = await resolveOrgRequest(request, orgId, 'sso:manage')
  if (ctx instanceof Response) return ctx

  const body = await readJson(request)
  const parsed = createSchema.safeParse(body)
  if (!parsed.success) return jsonError(400, errorText(request, 'domainRequired'))

  try {
    const doc = (await ctx.payload.create({
      collection: SSO_DOMAINS_SLUG,
      // The token is generated by the collection's `beforeValidate` hook (not writable by clients).
      data: { organization: ctx.orgId, domain: parsed.data.domain } as never,
      depth: 0,
      user: ctx.user,
      overrideAccess: false,
    })) as SsoDomain
    return Response.json({ doc: toDomainRow(doc) }, { status: 201 })
  } catch (error) {
    const message = errorMessage(error, request)
    return jsonError(
      errorStatus(error),
      /unique|duplicate|already/i.test(message) ? errorText(request, 'domainClaimed') : message,
    )
  }
}
