// Built-in types register themselves on import. Add new types below (one line each).
import './http'
import './keyword'
import './json-query'
import './port'
import './ping'
import './dns'
import './push'
import './group'
import './manual'
import './docker'
import './globalping'
// Protocols
import './grpc-keyword'
import './websocket-upgrade'
import './mqtt'
import './kafka-producer'
import './rabbitmq'
import './smtp'
import './snmp'
import './ntp'
import './sftp'
import './radius'
import './tailscale-ping'
import './real-browser'
// Databases
import './mysql'
import './postgres'
import './sqlserver'
import './mongodb'
import './redis'
// Game servers
import './steam'
import './gamedig'

export * from './registry'
export * from './types'
