// Marmot on Railway as code: services, Postgres, volumes and variables in one file.
//
//   pnpm railway:bootstrap     # first time: creates the project, secrets and domain
//   railway config plan        # later: preview changes against the linked project
//   railway config apply       # later: apply them
//
// Railway reads this file only when someone runs `railway config apply`; deploys use the settings it
// stored. Each service builds deploy/railway/<service>/Dockerfile, and those small images carry every
// fixed setting and the Marmot version. A release therefore reaches existing projects, and deploys of
// the published template, through the repository alone. deploy/railway/README.md describes the layout.
import { defineRailway, github, postgres, preserve, project, service, volume } from 'railway/iac'

const REPO = 'ThinkHumanDotDev/marmot'

export default defineRailway(() => {
  // Deploy from another branch (e.g. a PR under test) with MARMOT_BRANCH=feat/… when applying.
  const branch = process.env.MARMOT_BRANCH || 'main'
  // One region for every service, the database and the volumes (a volume must sit next to its service).
  // Volumes are declared with an explicit region and size because changing either later is destructive.
  const region = process.env.MARMOT_REGION || 'europe-west4-drams3a'
  // Build deploy/railway/<name>/Dockerfile from the repository root, so files such as
  // docker/Caddyfile are in the build context. Rebuild only when the inputs change.
  const fromRepo = (name: string, watch: string[] = []) => ({
    source: github(REPO, { branch }),
    build: {
      builder: 'DOCKERFILE' as const,
      dockerfilePath: `deploy/railway/${name}/Dockerfile`,
      watchPatterns: [`deploy/railway/${name}/**`, ...watch],
    },
    deploy: { restartPolicyType: 'ON_FAILURE' as const, restartPolicyMaxRetries: 10 },
    replicas: { [region]: 1 },
  })
  // Secrets are generated by bootstrap.sh on the first apply and kept as they are afterwards.
  const secret = (name: string) => process.env[name] || preserve()

  const db = postgres('Postgres', { region })
  const uploads = volume('uploads', { region, sizeMB: 5000 })
  const redisData = volume('redis-data', { region, sizeMB: 5000 })

  const redis = service('redis', {
    ...fromRepo('redis'),
    env: { REDIS_PASSWORD: secret('REDIS_PASSWORD') },
    volumeMounts: { '/data': redisData },
  })

  // Variables every Marmot role needs. The secret lives on web; the others reference it.
  const common = {
    NEXT_PUBLIC_SERVER_URL: 'https://${{edge.RAILWAY_PUBLIC_DOMAIN}}',
    DATABASE_URL: db.env.DATABASE_URL,
    // ?family=0: the private hostname can be IPv6-only, and ioredis looks up IPv4 by default.
    REDIS_URL:
      'redis://default:${{redis.REDIS_PASSWORD}}@${{redis.RAILWAY_PRIVATE_DOMAIN}}:6379?family=0',
  }

  const web = service('web', {
    ...fromRepo('web'),
    healthcheck: '/api/health',
    healthcheckTimeout: 300,
    // Railway injects PORT=8080 unless the service sets it; edge dials web on 3000.
    env: { ...common, PORT: '3000', PAYLOAD_SECRET: secret('PAYLOAD_SECRET') },
    volumeMounts: { '/app/uploads': uploads },
  })
  const worker = service('worker', {
    ...fromRepo('worker'),
    env: { ...common, PAYLOAD_SECRET: web.env.PAYLOAD_SECRET },
  })
  const realtime = service('realtime', {
    ...fromRepo('realtime'),
    healthcheck: '/healthz',
    healthcheckTimeout: 300,
    // PORT points Railway's healthcheck at the socket server, which listens on REALTIME_PORT (3001).
    env: { ...common, PORT: '3001', PAYLOAD_SECRET: web.env.PAYLOAD_SECRET },
  })

  // The only public service; bootstrap.sh generates its Railway domain on port 8080.
  const edge = service('edge', {
    ...fromRepo('edge', ['docker/Caddyfile']),
    env: { PORT: '8080' },
  })

  return project('marmot', {
    resources: [db, uploads, redisData, redis, web, worker, realtime, edge],
  })
})
