// Marmot on Railway as code: services, Postgres, volumes and variables in one file.
//
//   pnpm railway:bootstrap               # first time: creates the project, secrets, domain
//   pnpm exec railway config plan        # later: preview changes against the linked project
//   pnpm exec railway config apply       # later: apply them
//
// Build and deploy settings (Dockerfile, healthcheck, restart policy) stay in each service's
// deploy/railway/<service>/railway.json, which Railway reads on every deploy. That includes deploys
// of the published template, so a release reaches template users without anyone running this file.
// deploy/railway/README.md describes the layout.
import { defineRailway, github, postgres, preserve, project, service, volume } from 'railway/iac'

const REPO = 'ThinkHumanDotDev/marmot'

export default defineRailway(() => {
  // Deploy from another branch (e.g. a PR under test) with MARMOT_BRANCH=feat/… when applying.
  const branch = process.env.MARMOT_BRANCH || 'main'
  const fromRepo = (name: string) => ({
    source: github(REPO, { branch }),
    configFile: `deploy/railway/${name}/railway.json`,
  })
  // Secrets are generated by bootstrap.sh on the first apply and kept as they are afterwards.
  const secret = (name: string) => process.env[name] || preserve()

  const db = postgres('Postgres')
  const uploads = volume('uploads')
  const redisData = volume('redis-data')

  const redis = service('redis', {
    ...fromRepo('redis'),
    env: { REDIS_PASSWORD: secret('REDIS_PASSWORD') },
    volumeMounts: { '/data': redisData },
  })

  // Variables every Marmot role needs. The secret lives on web; the others reference it.
  const common = {
    NEXT_PUBLIC_SERVER_URL: 'https://${{edge.RAILWAY_PUBLIC_DOMAIN}}',
    DATABASE_URL: db.env.DATABASE_URL,
    // ?family=0: the private hostname can be IPv6-only, and ioredis looks up IPv4 by default.
    REDIS_URL:
      'redis://default:${{redis.REDIS_PASSWORD}}@${{redis.RAILWAY_PRIVATE_DOMAIN}}:6379?family=0',
  }

  const web = service('web', {
    ...fromRepo('web'),
    env: { ...common, PAYLOAD_SECRET: secret('PAYLOAD_SECRET') },
    volumeMounts: { '/app/uploads': uploads },
  })
  const worker = service('worker', {
    ...fromRepo('worker'),
    env: { ...common, PAYLOAD_SECRET: web.env.PAYLOAD_SECRET },
  })
  const realtime = service('realtime', {
    ...fromRepo('realtime'),
    env: { ...common, PAYLOAD_SECRET: web.env.PAYLOAD_SECRET },
  })

  // The only public service; bootstrap.sh generates its Railway domain on port 8080.
  const edge = service('edge', fromRepo('edge'))

  return project('marmot', {
    resources: [db, uploads, redisData, redis, web, worker, realtime, edge],
  })
})
