/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    'auth-accounts': AuthAccount;
    organizations: Organization;
    invitations: Invitation;
    media: Media;
    monitors: Monitor;
    notifications: Notification;
    tags: Tag;
    proxies: MonitorProxy;
    'docker-hosts': DockerHost;
    'notification-sent-history': NotificationSentHistory;
    heartbeats: Heartbeat;
    'stat-minutely': StatMinutely;
    'stat-hourly': StatHourly;
    'stat-daily': StatDaily;
    'status-pages': StatusPage;
    incidents: Incident;
    maintenance: Maintenance;
    'api-keys': ApiKey;
    'audit-logs': AuditLog;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    'auth-accounts': AuthAccountsSelect<false> | AuthAccountsSelect<true>;
    organizations: OrganizationsSelect<false> | OrganizationsSelect<true>;
    invitations: InvitationsSelect<false> | InvitationsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    monitors: MonitorsSelect<false> | MonitorsSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    proxies: ProxiesSelect<false> | ProxiesSelect<true>;
    'docker-hosts': DockerHostsSelect<false> | DockerHostsSelect<true>;
    'notification-sent-history': NotificationSentHistorySelect<false> | NotificationSentHistorySelect<true>;
    heartbeats: HeartbeatsSelect<false> | HeartbeatsSelect<true>;
    'stat-minutely': StatMinutelySelect<false> | StatMinutelySelect<true>;
    'stat-hourly': StatHourlySelect<false> | StatHourlySelect<true>;
    'stat-daily': StatDailySelect<false> | StatDailySelect<true>;
    'status-pages': StatusPagesSelect<false> | StatusPagesSelect<true>;
    incidents: IncidentsSelect<false> | IncidentsSelect<true>;
    maintenance: MaintenanceSelect<false> | MaintenanceSelect<true>;
    'api-keys': ApiKeysSelect<false> | ApiKeysSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'instance-settings': InstanceSetting;
  };
  globalsSelect: {
    'instance-settings': InstanceSettingsSelect<false> | InstanceSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  avatar?: (number | null) | Media;
  /**
   * Instance administrator: can access the Payload admin panel and every organization.
   */
  superadmin?: boolean | null;
  /**
   * How the account was created: password signup or single sign-on.
   */
  authProvider?: ('local' | 'oidc') | null;
  /**
   * Legacy: identities now live in Auth accounts.
   */
  oidcIssuer?: string | null;
  /**
   * Legacy `sub` claim; identities now live in Auth accounts.
   */
  oidcSubject?: string | null;
  /**
   * Colour scheme preference, applied on every device after sign-in.
   */
  theme?: ('system' | 'light' | 'dark') | null;
  /**
   * Managed from Settings → Account → Two-factor authentication.
   */
  twoFactorEnabled?: boolean | null;
  twoFactorVerifiedAt?: string | null;
  twoFactorSecret?: string | null;
  twoFactorPendingSecret?: string | null;
  twoFactorBackupCodes?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  twoFactorLastUsedStep?: number | null;
  organizations?:
    | {
        organization: number | Organization;
        role: 'owner' | 'admin' | 'member' | 'viewer';
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizations".
 */
export interface Organization {
  id: number;
  name: string;
  /**
   * Lowercase letters, numbers and hyphens. Used in URLs.
   */
  slug: string;
  logo?: (number | null) | Media;
  /**
   * Self-hosted installs are unlimited regardless of plan.
   */
  plan?: ('free' | 'team' | 'pro' | 'enterprise') | null;
  /**
   * Maintained by Stripe webhooks when billing is enabled.
   */
  subscriptionStatus?: ('none' | 'trialing' | 'active' | 'past_due' | 'canceled' | 'unpaid') | null;
  stripeCustomerId?: string | null;
  stripeSubscriptionId?: string | null;
  /**
   * Secret of the shareable invite link. Regenerate from the members page.
   */
  inviteLinkToken?: string | null;
  /**
   * Role granted to people who join through the invite link.
   */
  inviteLinkRole?: ('owner' | 'admin' | 'member' | 'viewer') | null;
  /**
   * Per-organization minimum roles, e.g. { "monitor:create": "admin" }. Unset permissions use the defaults in src/access/permissions.ts.
   */
  permissionOverrides?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  settings?: {
    /**
     * IANA time zone, e.g. Europe/London.
     */
    timezone?: string | null;
    weekStart?: ('monday' | 'sunday') | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Single sign-on identities linked to users. Managed by the login flows.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth-accounts".
 */
export interface AuthAccount {
  id: number;
  user: number | User;
  /**
   * Provider or connection id the identity came from.
   */
  provider: string;
  /**
   * Stable identifier at the provider (OIDC sub, OAuth id, SAML NameID).
   */
  providerAccountId: string;
  /**
   * Email the provider released, if any.
   */
  email?: string | null;
  name?: string | null;
  lastLoginAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invitations".
 */
export interface Invitation {
  id: number;
  organization: number | Organization;
  email: string;
  role: 'owner' | 'admin' | 'member' | 'viewer';
  /**
   * Generated on create.
   */
  token?: string | null;
  status?: ('pending' | 'accepted' | 'revoked' | 'expired') | null;
  expiresAt?: string | null;
  invitedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "monitors".
 */
export interface Monitor {
  id: number;
  organization: number | Organization;
  name: string;
  type:
    | 'http'
    | 'keyword'
    | 'json-query'
    | 'port'
    | 'ping'
    | 'dns'
    | 'push'
    | 'group'
    | 'manual'
    | 'docker'
    | 'grpc-keyword'
    | 'websocket-upgrade'
    | 'mqtt'
    | 'kafka-producer'
    | 'rabbitmq'
    | 'smtp'
    | 'snmp'
    | 'ntp'
    | 'sftp'
    | 'radius'
    | 'tailscale-ping'
    | 'real-browser'
    | 'mysql'
    | 'postgres'
    | 'sqlserver'
    | 'mongodb'
    | 'redis'
    | 'steam'
    | 'gamedig';
  /**
   * Paused monitors are not checked.
   */
  active?: boolean | null;
  /**
   * Group this monitor belongs to.
   */
  parent?: (number | null) | Monitor;
  description?: string | null;
  /**
   * Tags (optionally with a value, e.g. env: prod) shown as chips.
   */
  tags?:
    | {
        tag: number | Tag;
        value?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Channels alerted when this monitor changes status.
   */
  notifications?: (number | Notification)[] | null;
  /**
   * Sort order on status pages.
   */
  weight?: number | null;
  url?: string | null;
  /**
   * Send the request through this proxy (inactive proxies are skipped).
   */
  proxy?: (number | null) | MonitorProxy;
  dockerHost?: (number | null) | DockerHost;
  /**
   * Container name or id.
   */
  dockerContainer?: string | null;
  hostname?: string | null;
  /**
   * DNS monitors: port of the resolver (default 53).
   */
  port?: number | null;
  /**
   * Seconds between checks (UI minimum 20).
   */
  interval: number;
  /**
   * Seconds between checks while pending (retrying).
   */
  retryInterval: number;
  /**
   * Retries before the monitor is marked DOWN.
   */
  maxRetries: number;
  /**
   * Re-notify every N consecutive DOWN beats (0 = never).
   */
  resendInterval: number;
  /**
   * Request timeout in seconds (0 = 80% of the interval).
   */
  timeout: number;
  /**
   * Flip status: a failed check counts as UP and vice versa.
   */
  upsideDown?: boolean | null;
  method?: ('GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE' | 'HEAD' | 'OPTIONS') | null;
  httpBodyEncoding?: ('json' | 'form' | 'xml') | null;
  maxRedirects?: number | null;
  body?: string | null;
  /**
   * JSON object of extra request headers.
   */
  headers?: string | null;
  /**
   * Status codes or ranges counted as UP, e.g. 200-299, 304.
   */
  acceptedStatusCodes?: string[] | null;
  ignoreTls?: boolean | null;
  /**
   * Notify before the TLS certificate expires (tlsExpiryNotifyDays).
   */
  expiryNotification?: boolean | null;
  /**
   * Notify before the domain registration expires (domainExpiryNotifyDays).
   */
  domainExpiryNotification?: boolean | null;
  /**
   * Maintained by the worker: TLS certificate seen by the last HTTPS check.
   */
  certInfo?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Maintained by the worker: cached RDAP domain expiry lookup.
   */
  domainExpiry?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  keyword?: string | null;
  /**
   * UP when the keyword is absent.
   */
  invertKeyword?: boolean | null;
  /**
   * JSONata expression, e.g. `$.status` or `data[0].ok`.
   */
  jsonPath?: string | null;
  jsonPathOperator?: ('==' | '!=' | '<' | '>' | '<=' | '>=' | 'contains') | null;
  expectedValue?: string | null;
  authMethod?: ('none' | 'basic' | 'bearer' | 'oauth2-cc' | 'ntlm' | 'mtls') | null;
  basicAuthUser?: string | null;
  basicAuthPass?: string | null;
  authDomain?: string | null;
  authWorkstation?: string | null;
  bearerToken?: string | null;
  oauthTokenUrl?: string | null;
  oauthClientId?: string | null;
  oauthClientSecret?: string | null;
  oauthScopes?: string | null;
  oauthAuthMethod?: ('client_secret_basic' | 'client_secret_post') | null;
  tlsCert?: string | null;
  tlsKey?: string | null;
  tlsCa?: string | null;
  /**
   * Comma-separated resolver IPs or hostnames.
   */
  dnsResolveServer?: string | null;
  dnsResolveType?: ('A' | 'AAAA' | 'CAA' | 'CNAME' | 'MX' | 'NS' | 'PTR' | 'SOA' | 'SRV' | 'TXT') | null;
  /**
   * Generated automatically. Call /api/push/<token> to report a heartbeat.
   */
  pushToken?: string | null;
  manualStatus?: ('up' | 'down' | 'pending') | null;
  /**
   * Driver connection string, e.g. postgres://user:pass@host:5432/db, mysql://…, mongodb://…, redis://….
   */
  databaseConnectionString?: string | null;
  /**
   * SQL statement to run (default SELECT 1). MongoDB: JSON command document (default {"ping": 1}).
   */
  databaseQuery?: string | null;
  mqttTopic?: string | null;
  mqttUsername?: string | null;
  mqttPassword?: string | null;
  mqttCheckType?: ('keyword' | 'json-query') | null;
  /**
   * Keyword mode: the received message must contain this text.
   */
  mqttSuccessMessage?: string | null;
  /**
   * Broker addresses, e.g. kafka1:9092.
   */
  kafkaProducerBrokers?: string[] | null;
  kafkaProducerTopic?: string | null;
  kafkaProducerMessage?: string | null;
  kafkaProducerSsl?: boolean | null;
  kafkaProducerAllowAutoTopicCreation?: boolean | null;
  /**
   * JSON object with mechanism (plain, scram-sha-256, scram-sha-512) and username/password.
   */
  kafkaProducerSaslOptions?: string | null;
  grpcUrl?: string | null;
  grpcServiceName?: string | null;
  grpcMethod?: string | null;
  grpcEnableTls?: boolean | null;
  /**
   * Proto definition of the service.
   */
  grpcProtobuf?: string | null;
  /**
   * JSON request body.
   */
  grpcBody?: string | null;
  /**
   * JSON object of request metadata.
   */
  grpcMetadata?: string | null;
  radiusUsername?: string | null;
  radiusPassword?: string | null;
  radiusSecret?: string | null;
  radiusCalledStationId?: string | null;
  radiusCallingStationId?: string | null;
  snmpOid?: string | null;
  snmpVersion?: ('1' | '2c') | null;
  snmpCommunity?: string | null;
  smtpSecurity?: ('opportunistic' | 'starttls' | 'secure' | 'nostarttls') | null;
  sshUsername?: string | null;
  sshAuthMethod?: ('password' | 'privateKey') | null;
  sshPassword?: string | null;
  sshPrivateKey?: string | null;
  sshPassphrase?: string | null;
  /**
   * Optional remote path that must exist.
   */
  sftpPath?: string | null;
  /**
   * Management API base URLs, e.g. https://node1:15672.
   */
  rabbitmqNodes?: string[] | null;
  rabbitmqUsername?: string | null;
  rabbitmqPassword?: string | null;
  /**
   * Comma-separated Sec-WebSocket-Protocol values.
   */
  wsSubprotocol?: string | null;
  /**
   * Accept non-compliant servers that omit Sec-WebSocket-Accept.
   */
  wsIgnoreSecWebsocketAcceptHeader?: boolean | null;
  /**
   * GameDig game id, e.g. minecraft.
   */
  game?: string | null;
  /**
   * Do not probe the other ports a game commonly uses.
   */
  gamedigGivenPortOnly?: boolean | null;
  /**
   * Playwright-compatible remote browser websocket URL.
   */
  remoteBrowser?: string | null;
  /**
   * Maintained by the worker. Mirrors the latest heartbeat.
   */
  status?: {
    lastStatus?: ('up' | 'down' | 'pending' | 'maintenance') | null;
    lastCheckAt?: string | null;
    lastPing?: number | null;
    lastMsg?: string | null;
    retries?: number | null;
    downCount?: number | null;
    /**
     * Push monitors: time of the last call to the push endpoint.
     */
    lastPushAt?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  organization: number | Organization;
  name: string;
  /**
   * Hex colour of the chip, e.g. #2563EB.
   */
  color: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: number;
  organization: number | Organization;
  name: string;
  /**
   * Provider slug, e.g. discord, slack, smtp (see docs/Notifications.md).
   */
  type: string;
  /**
   * Provider-specific settings; validated against the provider schema.
   */
  config:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Attach this channel to every new monitor of the organization.
   */
  isDefault?: boolean | null;
  /**
   * On save, also attach this channel to all existing monitors.
   */
  applyExisting?: boolean | null;
  /**
   * Inactive channels are never sent to.
   */
  active?: boolean | null;
  /**
   * Maintained by the worker.
   */
  lastSentAt?: string | null;
  /**
   * Last delivery error; cleared on the next success.
   */
  lastError?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "proxies".
 */
export interface MonitorProxy {
  id: number;
  organization: number | Organization;
  protocol: 'http' | 'https' | 'socks' | 'socks5' | 'socks5h' | 'socks4';
  host: string;
  port: number;
  /**
   * The proxy requires a username and password.
   */
  auth?: boolean | null;
  username?: string | null;
  /**
   * Only visible to users who may edit proxies.
   */
  password?: string | null;
  /**
   * Inactive proxies are ignored: monitors connect directly.
   */
  active?: boolean | null;
  /**
   * Preselected for new HTTP monitors. One per organization.
   */
  default?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "docker-hosts".
 */
export interface DockerHost {
  id: number;
  organization: number | Organization;
  name: string;
  connectionType: 'socket' | 'tcp';
  /**
   * Unix socket of the Docker daemon, as seen by the worker.
   */
  socketPath?: string | null;
  /**
   * tcp:// and http:// connect in plain text; https:// uses TLS.
   */
  url?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Expiry warnings already sent per monitor and threshold. Maintained by the worker.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notification-sent-history".
 */
export interface NotificationSentHistory {
  id: number;
  /**
   * Denormalised from the monitor for org-scoped queries.
   */
  organization?: (number | null) | Organization;
  monitor: number | Monitor;
  type: 'certificate' | 'domain';
  /**
   * Threshold (days before expiry) the warning was sent for.
   */
  days: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "heartbeats".
 */
export interface Heartbeat {
  id: number;
  monitor: number | Monitor;
  /**
   * Denormalised from the monitor for org-scoped queries.
   */
  organization?: (number | null) | Organization;
  status: 'up' | 'down' | 'pending' | 'maintenance';
  msg?: string | null;
  /**
   * Response time in milliseconds (null when not measured).
   */
  ping?: number | null;
  /**
   * Seconds since the previous heartbeat of this monitor.
   */
  duration?: number | null;
  /**
   * True when the status changed compared to the previous heartbeat.
   */
  important?: boolean | null;
  retries?: number | null;
  downCount?: number | null;
  time: string;
}
/**
 * Per-monitor heartbeat aggregates, one row per minute.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stat-minutely".
 */
export interface StatMinutely {
  id: number;
  monitor: number | Monitor;
  organization: number | Organization;
  /**
   * Unix seconds, truncated to the start of the minute (UTC).
   */
  timestamp: number;
  up: number;
  down: number;
  /**
   * Average ping (ms) of UP beats.
   */
  ping?: number | null;
  pingMin?: number | null;
  pingMax?: number | null;
  /**
   * Additional counters, e.g. { maintenance, pingCount }.
   */
  extras?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * Per-monitor heartbeat aggregates, one row per hour.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stat-hourly".
 */
export interface StatHourly {
  id: number;
  monitor: number | Monitor;
  organization: number | Organization;
  /**
   * Unix seconds, truncated to the start of the hour (UTC).
   */
  timestamp: number;
  up: number;
  down: number;
  /**
   * Average ping (ms) of UP beats.
   */
  ping?: number | null;
  pingMin?: number | null;
  pingMax?: number | null;
  /**
   * Additional counters, e.g. { maintenance, pingCount }.
   */
  extras?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * Per-monitor heartbeat aggregates, one row per day.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stat-daily".
 */
export interface StatDaily {
  id: number;
  monitor: number | Monitor;
  organization: number | Organization;
  /**
   * Unix seconds, truncated to the start of the day (UTC).
   */
  timestamp: number;
  up: number;
  down: number;
  /**
   * Average ping (ms) of UP beats.
   */
  ping?: number | null;
  pingMin?: number | null;
  pingMax?: number | null;
  /**
   * Additional counters, e.g. { maintenance, pingCount }.
   */
  extras?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "status-pages".
 */
export interface StatusPage {
  id: number;
  organization: number | Organization;
  title: string;
  /**
   * Public URL: /status/<slug>. Lowercase letters, numbers, hyphens.
   */
  slug: string;
  description?: string | null;
  logo?: (number | null) | Media;
  theme?: ('auto' | 'light' | 'dark') | null;
  /**
   * Unpublished pages return 404 to visitors.
   */
  published?: boolean | null;
  searchEngineIndex?: boolean | null;
  showTags?: boolean | null;
  showCertificateExpiry?: boolean | null;
  showPoweredBy?: boolean | null;
  /**
   * Seconds between client refreshes; 0 disables auto refresh.
   */
  autoRefreshInterval?: number | null;
  footerText?: string | null;
  /**
   * Injected into the public page as a <style> tag.
   */
  customCSS?: string | null;
  googleAnalyticsId?: string | null;
  /**
   * Custom hostnames that serve this page at their root (CNAME them to this server).
   */
  domains?:
    | {
        hostname: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Monitors are shown in these groups, in this order.
   */
  groups?:
    | {
        name: string;
        monitors?:
          | {
              monitor: number | Monitor;
              /**
               * Show the monitor's URL to visitors.
               */
              sendUrl?: boolean | null;
              /**
               * Link visitors to this URL instead.
               */
              customUrl?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "incidents".
 */
export interface Incident {
  id: number;
  /**
   * Derived from the status page.
   */
  organization: number | Organization;
  statusPage: number | StatusPage;
  title: string;
  /**
   * Markdown: paragraphs, **bold**, _italics_, `code` and links.
   */
  content?: string | null;
  style?: ('info' | 'warning' | 'danger' | 'primary') | null;
  /**
   * Pinned incidents are shown above the monitor groups.
   */
  pinned?: boolean | null;
  /**
   * Uncheck to resolve the incident.
   */
  active?: boolean | null;
  resolvedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "maintenance".
 */
export interface Maintenance {
  id: number;
  organization: number | Organization;
  title: string;
  /**
   * Shown on status pages.
   */
  description?: string | null;
  strategy: 'manual' | 'single' | 'recurring-interval' | 'recurring-weekday' | 'recurring-day-of-month' | 'cron';
  /**
   * IANA time zone the schedule is written in, or SAME_AS_SERVER for the organization's zone.
   */
  timezone?: string | null;
  /**
   * Paused maintenances never run.
   */
  active?: boolean | null;
  /**
   * Maintained by the server; recomputed every minute.
   */
  status?: ('inactive' | 'scheduled' | 'under-maintenance' | 'ended' | 'unknown') | null;
  /**
   * Single window: when it runs. Recurring/cron: optional effective range. Wall-clock in the time zone above (YYYY-MM-DDTHH:mm).
   */
  dateRange?: {
    start?: string | null;
    end?: string | null;
  };
  /**
   * Daily window (HH:mm); an end before the start runs past midnight.
   */
  timeRange?: {
    start?: string | null;
    end?: string | null;
  };
  /**
   * Run every N days, counted from the start date.
   */
  intervalDay?: number | null;
  weekdays?: ('1' | '2' | '3' | '4' | '5' | '6' | '0')[] | null;
  /**
   * Only "Last day of the month" has a cron equivalent; 2nd–4th last are ignored.
   */
  daysOfMonth?:
    | (
        | '1'
        | '2'
        | '3'
        | '4'
        | '5'
        | '6'
        | '7'
        | '8'
        | '9'
        | '10'
        | '11'
        | '12'
        | '13'
        | '14'
        | '15'
        | '16'
        | '17'
        | '18'
        | '19'
        | '20'
        | '21'
        | '22'
        | '23'
        | '24'
        | '25'
        | '26'
        | '27'
        | '28'
        | '29'
        | '30'
        | '31'
        | 'lastDay1'
        | 'lastDay2'
        | 'lastDay3'
        | 'lastDay4'
      )[]
    | null;
  /**
   * Five-field cron expression, evaluated in the time zone.
   */
  cron?: string | null;
  /**
   * Minutes each occurrence lasts.
   */
  duration?: number | null;
  /**
   * Affected monitors: checks are skipped and MAINTENANCE heartbeats written.
   */
  monitors?: (number | Monitor)[] | null;
  /**
   * Status pages that announce this maintenance.
   */
  statusPages?: (number | StatusPage)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "api-keys".
 */
export interface ApiKey {
  id: number;
  organization: number | Organization;
  name: string;
  /**
   * SHA-256 of the plaintext key.
   */
  keyHash: string;
  /**
   * Public identifier shown in the UI (mk_<prefix>).
   */
  prefix: string;
  /**
   * Disabled keys are rejected.
   */
  active?: boolean | null;
  /**
   * Leave empty for a key that never expires.
   */
  expiresAt?: string | null;
  lastUsedAt?: string | null;
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Security-relevant events. Rows are written by the server and cannot be edited.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: number;
  action: string;
  actor?: (number | null) | User;
  organization?: (number | null) | Organization;
  /**
   * Affected record, e.g. user:42.
   */
  target?: string | null;
  ip?: string | null;
  userAgent?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'auth-accounts';
        value: number | AuthAccount;
      } | null)
    | ({
        relationTo: 'organizations';
        value: number | Organization;
      } | null)
    | ({
        relationTo: 'invitations';
        value: number | Invitation;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'monitors';
        value: number | Monitor;
      } | null)
    | ({
        relationTo: 'notifications';
        value: number | Notification;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'proxies';
        value: number | MonitorProxy;
      } | null)
    | ({
        relationTo: 'docker-hosts';
        value: number | DockerHost;
      } | null)
    | ({
        relationTo: 'notification-sent-history';
        value: number | NotificationSentHistory;
      } | null)
    | ({
        relationTo: 'heartbeats';
        value: number | Heartbeat;
      } | null)
    | ({
        relationTo: 'stat-minutely';
        value: number | StatMinutely;
      } | null)
    | ({
        relationTo: 'stat-hourly';
        value: number | StatHourly;
      } | null)
    | ({
        relationTo: 'stat-daily';
        value: number | StatDaily;
      } | null)
    | ({
        relationTo: 'status-pages';
        value: number | StatusPage;
      } | null)
    | ({
        relationTo: 'incidents';
        value: number | Incident;
      } | null)
    | ({
        relationTo: 'maintenance';
        value: number | Maintenance;
      } | null)
    | ({
        relationTo: 'api-keys';
        value: number | ApiKey;
      } | null)
    | ({
        relationTo: 'audit-logs';
        value: number | AuditLog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  avatar?: T;
  superadmin?: T;
  authProvider?: T;
  oidcIssuer?: T;
  oidcSubject?: T;
  theme?: T;
  twoFactorEnabled?: T;
  twoFactorVerifiedAt?: T;
  twoFactorSecret?: T;
  twoFactorPendingSecret?: T;
  twoFactorBackupCodes?: T;
  twoFactorLastUsedStep?: T;
  organizations?:
    | T
    | {
        organization?: T;
        role?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth-accounts_select".
 */
export interface AuthAccountsSelect<T extends boolean = true> {
  user?: T;
  provider?: T;
  providerAccountId?: T;
  email?: T;
  name?: T;
  lastLoginAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizations_select".
 */
export interface OrganizationsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  logo?: T;
  plan?: T;
  subscriptionStatus?: T;
  stripeCustomerId?: T;
  stripeSubscriptionId?: T;
  inviteLinkToken?: T;
  inviteLinkRole?: T;
  permissionOverrides?: T;
  settings?:
    | T
    | {
        timezone?: T;
        weekStart?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invitations_select".
 */
export interface InvitationsSelect<T extends boolean = true> {
  organization?: T;
  email?: T;
  role?: T;
  token?: T;
  status?: T;
  expiresAt?: T;
  invitedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "monitors_select".
 */
export interface MonitorsSelect<T extends boolean = true> {
  organization?: T;
  name?: T;
  type?: T;
  active?: T;
  parent?: T;
  description?: T;
  tags?:
    | T
    | {
        tag?: T;
        value?: T;
        id?: T;
      };
  notifications?: T;
  weight?: T;
  url?: T;
  proxy?: T;
  dockerHost?: T;
  dockerContainer?: T;
  hostname?: T;
  port?: T;
  interval?: T;
  retryInterval?: T;
  maxRetries?: T;
  resendInterval?: T;
  timeout?: T;
  upsideDown?: T;
  method?: T;
  httpBodyEncoding?: T;
  maxRedirects?: T;
  body?: T;
  headers?: T;
  acceptedStatusCodes?: T;
  ignoreTls?: T;
  expiryNotification?: T;
  domainExpiryNotification?: T;
  certInfo?: T;
  domainExpiry?: T;
  keyword?: T;
  invertKeyword?: T;
  jsonPath?: T;
  jsonPathOperator?: T;
  expectedValue?: T;
  authMethod?: T;
  basicAuthUser?: T;
  basicAuthPass?: T;
  authDomain?: T;
  authWorkstation?: T;
  bearerToken?: T;
  oauthTokenUrl?: T;
  oauthClientId?: T;
  oauthClientSecret?: T;
  oauthScopes?: T;
  oauthAuthMethod?: T;
  tlsCert?: T;
  tlsKey?: T;
  tlsCa?: T;
  dnsResolveServer?: T;
  dnsResolveType?: T;
  pushToken?: T;
  manualStatus?: T;
  databaseConnectionString?: T;
  databaseQuery?: T;
  mqttTopic?: T;
  mqttUsername?: T;
  mqttPassword?: T;
  mqttCheckType?: T;
  mqttSuccessMessage?: T;
  kafkaProducerBrokers?: T;
  kafkaProducerTopic?: T;
  kafkaProducerMessage?: T;
  kafkaProducerSsl?: T;
  kafkaProducerAllowAutoTopicCreation?: T;
  kafkaProducerSaslOptions?: T;
  grpcUrl?: T;
  grpcServiceName?: T;
  grpcMethod?: T;
  grpcEnableTls?: T;
  grpcProtobuf?: T;
  grpcBody?: T;
  grpcMetadata?: T;
  radiusUsername?: T;
  radiusPassword?: T;
  radiusSecret?: T;
  radiusCalledStationId?: T;
  radiusCallingStationId?: T;
  snmpOid?: T;
  snmpVersion?: T;
  snmpCommunity?: T;
  smtpSecurity?: T;
  sshUsername?: T;
  sshAuthMethod?: T;
  sshPassword?: T;
  sshPrivateKey?: T;
  sshPassphrase?: T;
  sftpPath?: T;
  rabbitmqNodes?: T;
  rabbitmqUsername?: T;
  rabbitmqPassword?: T;
  wsSubprotocol?: T;
  wsIgnoreSecWebsocketAcceptHeader?: T;
  game?: T;
  gamedigGivenPortOnly?: T;
  remoteBrowser?: T;
  status?:
    | T
    | {
        lastStatus?: T;
        lastCheckAt?: T;
        lastPing?: T;
        lastMsg?: T;
        retries?: T;
        downCount?: T;
        lastPushAt?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  organization?: T;
  name?: T;
  type?: T;
  config?: T;
  isDefault?: T;
  applyExisting?: T;
  active?: T;
  lastSentAt?: T;
  lastError?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  organization?: T;
  name?: T;
  color?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "proxies_select".
 */
export interface ProxiesSelect<T extends boolean = true> {
  organization?: T;
  protocol?: T;
  host?: T;
  port?: T;
  auth?: T;
  username?: T;
  password?: T;
  active?: T;
  default?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "docker-hosts_select".
 */
export interface DockerHostsSelect<T extends boolean = true> {
  organization?: T;
  name?: T;
  connectionType?: T;
  socketPath?: T;
  url?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notification-sent-history_select".
 */
export interface NotificationSentHistorySelect<T extends boolean = true> {
  organization?: T;
  monitor?: T;
  type?: T;
  days?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "heartbeats_select".
 */
export interface HeartbeatsSelect<T extends boolean = true> {
  monitor?: T;
  organization?: T;
  status?: T;
  msg?: T;
  ping?: T;
  duration?: T;
  important?: T;
  retries?: T;
  downCount?: T;
  time?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stat-minutely_select".
 */
export interface StatMinutelySelect<T extends boolean = true> {
  monitor?: T;
  organization?: T;
  timestamp?: T;
  up?: T;
  down?: T;
  ping?: T;
  pingMin?: T;
  pingMax?: T;
  extras?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stat-hourly_select".
 */
export interface StatHourlySelect<T extends boolean = true> {
  monitor?: T;
  organization?: T;
  timestamp?: T;
  up?: T;
  down?: T;
  ping?: T;
  pingMin?: T;
  pingMax?: T;
  extras?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stat-daily_select".
 */
export interface StatDailySelect<T extends boolean = true> {
  monitor?: T;
  organization?: T;
  timestamp?: T;
  up?: T;
  down?: T;
  ping?: T;
  pingMin?: T;
  pingMax?: T;
  extras?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "status-pages_select".
 */
export interface StatusPagesSelect<T extends boolean = true> {
  organization?: T;
  title?: T;
  slug?: T;
  description?: T;
  logo?: T;
  theme?: T;
  published?: T;
  searchEngineIndex?: T;
  showTags?: T;
  showCertificateExpiry?: T;
  showPoweredBy?: T;
  autoRefreshInterval?: T;
  footerText?: T;
  customCSS?: T;
  googleAnalyticsId?: T;
  domains?:
    | T
    | {
        hostname?: T;
        id?: T;
      };
  groups?:
    | T
    | {
        name?: T;
        monitors?:
          | T
          | {
              monitor?: T;
              sendUrl?: T;
              customUrl?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "incidents_select".
 */
export interface IncidentsSelect<T extends boolean = true> {
  organization?: T;
  statusPage?: T;
  title?: T;
  content?: T;
  style?: T;
  pinned?: T;
  active?: T;
  resolvedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "maintenance_select".
 */
export interface MaintenanceSelect<T extends boolean = true> {
  organization?: T;
  title?: T;
  description?: T;
  strategy?: T;
  timezone?: T;
  active?: T;
  status?: T;
  dateRange?:
    | T
    | {
        start?: T;
        end?: T;
      };
  timeRange?:
    | T
    | {
        start?: T;
        end?: T;
      };
  intervalDay?: T;
  weekdays?: T;
  daysOfMonth?: T;
  cron?: T;
  duration?: T;
  monitors?: T;
  statusPages?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "api-keys_select".
 */
export interface ApiKeysSelect<T extends boolean = true> {
  organization?: T;
  name?: T;
  keyHash?: T;
  prefix?: T;
  active?: T;
  expiresAt?: T;
  lastUsedAt?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  action?: T;
  actor?: T;
  organization?: T;
  target?: T;
  ip?: T;
  userAgent?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "instance-settings".
 */
export interface InstanceSetting {
  id: number;
  /**
   * Public URL of this instance, used in notifications and status page links. Defaults to NEXT_PUBLIC_SERVER_URL.
   */
  primaryBaseUrl?: string | null;
  /**
   * Allow anyone to create an account. When off, only invited users can register. Defaults to the inverse of DISABLE_SIGNUP.
   */
  allowSignup?: boolean | null;
  /**
   * What visitors of the root URL see.
   */
  entryPage?: ('dashboard' | 'status-page') | null;
  /**
   * Notify this many days before a TLS certificate expires.
   */
  tlsExpiryNotifyDays?: number[] | null;
  /**
   * Notify this many days before a domain registration expires.
   */
  domainExpiryNotifyDays?: number[] | null;
  /**
   * Retention of daily aggregates and important heartbeats, in days (0 disables pruning). Defaults to KEEP_DATA_PERIOD_DAYS.
   */
  keepDataPeriodDays?: number | null;
  /**
   * Trust X-Forwarded-* headers from the reverse proxy when determining client IPs.
   */
  trustProxy?: boolean | null;
  /**
   * Steam Web API key for Steam Game Server monitors.
   */
  steamApiKey?: string | null;
  /**
   * Globalping API token for remote ping/HTTP checks.
   */
  globalpingApiToken?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "instance-settings_select".
 */
export interface InstanceSettingsSelect<T extends boolean = true> {
  primaryBaseUrl?: T;
  allowSignup?: T;
  entryPage?: T;
  tlsExpiryNotifyDays?: T;
  domainExpiryNotifyDays?: T;
  keepDataPeriodDays?: T;
  trustProxy?: T;
  steamApiKey?: T;
  globalpingApiToken?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}