/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    'auth-accounts': AuthAccount;
    organizations: Organization;
    'sso-connections': SsoConnection;
    'sso-domains': SsoDomain;
    invitations: Invitation;
    media: Media;
    monitors: Monitor;
    notifications: Notification;
    tags: Tag;
    proxies: MonitorProxy;
    'docker-hosts': DockerHost;
    locations: Location;
    'notification-sent-history': NotificationSentHistory;
    heartbeats: Heartbeat;
    'monitor-incidents': MonitorIncident;
    'push-events': PushEvent;
    'stat-minutely': StatMinutely;
    'stat-hourly': StatHourly;
    'stat-daily': StatDaily;
    'status-pages': StatusPage;
    'status-page-viewers': StatusPageViewer;
    incidents: Incident;
    'status-page-subscribers': StatusPageSubscriber;
    'subscriber-notifications': SubscriberNotification;
    'subscriber-deliveries': SubscriberDelivery;
    maintenance: Maintenance;
    'maintenance-occurrences': MaintenanceOccurrence;
    templates: Template;
    'api-keys': ApiKey;
    'audit-logs': AuditLog;
    'webhook-endpoints': WebhookEndpoint;
    'webhook-deliveries': WebhookDelivery;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    'auth-accounts': AuthAccountsSelect<false> | AuthAccountsSelect<true>;
    organizations: OrganizationsSelect<false> | OrganizationsSelect<true>;
    'sso-connections': SsoConnectionsSelect<false> | SsoConnectionsSelect<true>;
    'sso-domains': SsoDomainsSelect<false> | SsoDomainsSelect<true>;
    invitations: InvitationsSelect<false> | InvitationsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    monitors: MonitorsSelect<false> | MonitorsSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    proxies: ProxiesSelect<false> | ProxiesSelect<true>;
    'docker-hosts': DockerHostsSelect<false> | DockerHostsSelect<true>;
    locations: LocationsSelect<false> | LocationsSelect<true>;
    'notification-sent-history': NotificationSentHistorySelect<false> | NotificationSentHistorySelect<true>;
    heartbeats: HeartbeatsSelect<false> | HeartbeatsSelect<true>;
    'monitor-incidents': MonitorIncidentsSelect<false> | MonitorIncidentsSelect<true>;
    'push-events': PushEventsSelect<false> | PushEventsSelect<true>;
    'stat-minutely': StatMinutelySelect<false> | StatMinutelySelect<true>;
    'stat-hourly': StatHourlySelect<false> | StatHourlySelect<true>;
    'stat-daily': StatDailySelect<false> | StatDailySelect<true>;
    'status-pages': StatusPagesSelect<false> | StatusPagesSelect<true>;
    'status-page-viewers': StatusPageViewersSelect<false> | StatusPageViewersSelect<true>;
    incidents: IncidentsSelect<false> | IncidentsSelect<true>;
    'status-page-subscribers': StatusPageSubscribersSelect<false> | StatusPageSubscribersSelect<true>;
    'subscriber-notifications': SubscriberNotificationsSelect<false> | SubscriberNotificationsSelect<true>;
    'subscriber-deliveries': SubscriberDeliveriesSelect<false> | SubscriberDeliveriesSelect<true>;
    maintenance: MaintenanceSelect<false> | MaintenanceSelect<true>;
    'maintenance-occurrences': MaintenanceOccurrencesSelect<false> | MaintenanceOccurrencesSelect<true>;
    templates: TemplatesSelect<false> | TemplatesSelect<true>;
    'api-keys': ApiKeysSelect<false> | ApiKeysSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    'webhook-endpoints': WebhookEndpointsSelect<false> | WebhookEndpointsSelect<true>;
    'webhook-deliveries': WebhookDeliveriesSelect<false> | WebhookDeliveriesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'instance-settings': InstanceSetting;
  };
  globalsSelect: {
    'instance-settings': InstanceSettingsSelect<false> | InstanceSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  avatar?: (number | null) | Media;
  superadmin?: boolean | null;
  authProvider?: ('local' | 'oidc' | 'oauth' | 'saml') | null;
  oidcIssuer?: string | null;
  oidcSubject?: string | null;
  theme?: ('system' | 'light' | 'dark') | null;
  language?: 'en' | null;
  twoFactorEnabled?: boolean | null;
  twoFactorVerifiedAt?: string | null;
  twoFactorSecret?: string | null;
  twoFactorPendingSecret?: string | null;
  twoFactorBackupCodes?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  twoFactorLastUsedStep?: number | null;
  organizations?:
    | {
        organization: number | Organization;
        role: 'owner' | 'admin' | 'member' | 'viewer';
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizations".
 */
export interface Organization {
  id: number;
  name: string;
  slug: string;
  logo?: (number | null) | Media;
  plan?: ('free' | 'team' | 'pro' | 'enterprise') | null;
  subscriptionStatus?: ('none' | 'trialing' | 'active' | 'past_due' | 'canceled' | 'unpaid') | null;
  stripeCustomerId?: string | null;
  stripeSubscriptionId?: string | null;
  inviteLinkToken?: string | null;
  inviteLinkRole?: ('owner' | 'admin' | 'member' | 'viewer') | null;
  permissionOverrides?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  enforceSso?: boolean | null;
  settings?: {
    timezone?: string | null;
    weekStart?: ('monday' | 'sunday') | null;
    language?: 'en' | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth-accounts".
 */
export interface AuthAccount {
  id: number;
  user: number | User;
  /**
   * Provider or connection id the identity came from.
   */
  provider: string;
  /**
   * Stable identifier at the provider (OIDC sub, OAuth id, SAML NameID).
   */
  providerAccountId: string;
  /**
   * Email the provider released, if any.
   */
  email?: string | null;
  name?: string | null;
  lastLoginAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sso-connections".
 */
export interface SsoConnection {
  id: number;
  organization: number | Organization;
  name: string;
  slug: string;
  type: 'oidc' | 'saml';
  enabled?: boolean | null;
  issuerUrl?: string | null;
  clientId?: string | null;
  clientSecret?: string | null;
  scopes?: string | null;
  idpEntryPoint?: string | null;
  idpEntityId?: string | null;
  idpCert?: string | null;
  wantAssertionsSigned?: boolean | null;
  allowIdpInitiated?: boolean | null;
  autoProvision?: boolean | null;
  defaultRole?: ('admin' | 'member' | 'viewer') | null;
  groupClaim?: string | null;
  allowedGroups?: string | null;
  groupRoles?:
    | {
        group: string;
        role: 'owner' | 'admin' | 'member' | 'viewer';
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sso-domains".
 */
export interface SsoDomain {
  id: number;
  organization: number | Organization;
  domain: string;
  verificationToken: string;
  verifiedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invitations".
 */
export interface Invitation {
  id: number;
  organization: number | Organization;
  email: string;
  role: 'owner' | 'admin' | 'member' | 'viewer';
  token?: string | null;
  status?: ('pending' | 'accepted' | 'revoked' | 'expired') | null;
  expiresAt?: string | null;
  invitedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "monitors".
 */
export interface Monitor {
  id: number;
  organization: number | Organization;
  name: string;
  type:
    | 'http'
    | 'keyword'
    | 'json-query'
    | 'port'
    | 'ping'
    | 'dns'
    | 'globalping'
    | 'push'
    | 'group'
    | 'manual'
    | 'docker'
    | 'grpc-keyword'
    | 'websocket-upgrade'
    | 'mqtt'
    | 'kafka-producer'
    | 'rabbitmq'
    | 'smtp'
    | 'snmp'
    | 'ntp'
    | 'sftp'
    | 'radius'
    | 'tailscale-ping'
    | 'real-browser'
    | 'mysql'
    | 'postgres'
    | 'sqlserver'
    | 'mongodb'
    | 'redis'
    | 'steam'
    | 'gamedig';
  active?: boolean | null;
  parent?: (number | null) | Monitor;
  key?: string | null;
  publicName?: string | null;
  description?: string | null;
  tags?:
    | {
        tag: number | Tag;
        value?: string | null;
        id?: string | null;
      }[]
    | null;
  notifications?: (number | Notification)[] | null;
  locations?: (number | Location)[] | null;
  weight?: number | null;
  url?: string | null;
  proxy?: (number | null) | MonitorProxy;
  dockerHost?: (number | null) | DockerHost;
  dockerContainer?: string | null;
  hostname?: string | null;
  port?: number | null;
  interval: number;
  retryInterval: number;
  maxRetries: number;
  resendInterval: number;
  timeout: number;
  degradedAfter?: number | null;
  successThreshold?: number | null;
  reminderBackoff?: ('none' | 'linear' | 'exponential') | null;
  maxReminders?: number | null;
  upsideDown?: boolean | null;
  method?: ('GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE' | 'HEAD' | 'OPTIONS') | null;
  httpBodyEncoding?: ('json' | 'form' | 'xml') | null;
  maxRedirects?: number | null;
  body?: string | null;
  headers?: string | null;
  acceptedStatusCodes?: string[] | null;
  ignoreTls?: boolean | null;
  expiryNotification?: boolean | null;
  domainExpiryNotification?: boolean | null;
  certInfo?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  domainExpiry?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  keyword?: string | null;
  invertKeyword?: boolean | null;
  jsonPath?: string | null;
  jsonPathOperator?: ('==' | '!=' | '<' | '>' | '<=' | '>=' | 'contains') | null;
  expectedValue?: string | null;
  assertions?:
    | {
        kind: 'status' | 'header' | 'textBody' | 'jsonBody' | 'dnsRecord';
        target?: string | null;
        comparator:
          | 'eq'
          | 'not_eq'
          | 'gt'
          | 'gte'
          | 'lt'
          | 'lte'
          | 'contains'
          | 'not_contains'
          | 'empty'
          | 'not_empty'
          | 'matches'
          | 'not_matches';
        value?: string | null;
        id?: string | null;
      }[]
    | null;
  authMethod?: ('none' | 'basic' | 'bearer' | 'oauth2-cc' | 'ntlm' | 'mtls') | null;
  basicAuthUser?: string | null;
  basicAuthPass?: string | null;
  authDomain?: string | null;
  authWorkstation?: string | null;
  bearerToken?: string | null;
  oauthTokenUrl?: string | null;
  oauthClientId?: string | null;
  oauthClientSecret?: string | null;
  oauthScopes?: string | null;
  oauthAuthMethod?: ('client_secret_basic' | 'client_secret_post') | null;
  tlsCert?: string | null;
  tlsKey?: string | null;
  tlsCa?: string | null;
  dnsResolveServer?: string | null;
  dnsResolveType?: ('A' | 'AAAA' | 'CAA' | 'CNAME' | 'MX' | 'NS' | 'PTR' | 'SOA' | 'SRV' | 'TXT') | null;
  globalpingMeasurement?: ('ping' | 'http' | 'dns' | 'traceroute') | null;
  globalpingProtocol?: ('ICMP' | 'TCP' | 'UDP' | 'HTTP' | 'HTTPS' | 'HTTP2') | null;
  globalpingIpVersion?: ('4' | '6') | null;
  globalpingLocations?: string | null;
  globalpingProbes?: number | null;
  globalpingSuccessRule?: ('all' | 'any' | 'atLeast') | null;
  globalpingMinSuccess?: number | null;
  globalpingPackets?: number | null;
  pushToken?: string | null;
  pushSchedule?: ('interval' | 'cron') | null;
  pushCron?: string | null;
  pushTimezone?: string | null;
  pushGrace?: number | null;
  pushMaxDuration?: number | null;
  manualStatus?: ('up' | 'down' | 'pending') | null;
  databaseConnectionString?: string | null;
  databaseQuery?: string | null;
  mqttTopic?: string | null;
  mqttUsername?: string | null;
  mqttPassword?: string | null;
  mqttCheckType?: ('keyword' | 'json-query') | null;
  mqttSuccessMessage?: string | null;
  kafkaProducerBrokers?: string[] | null;
  kafkaProducerTopic?: string | null;
  kafkaProducerMessage?: string | null;
  kafkaProducerSsl?: boolean | null;
  kafkaProducerAllowAutoTopicCreation?: boolean | null;
  kafkaProducerSaslOptions?: string | null;
  grpcUrl?: string | null;
  grpcServiceName?: string | null;
  grpcMethod?: string | null;
  grpcEnableTls?: boolean | null;
  grpcProtobuf?: string | null;
  grpcBody?: string | null;
  grpcMetadata?: string | null;
  radiusUsername?: string | null;
  radiusPassword?: string | null;
  radiusSecret?: string | null;
  radiusCalledStationId?: string | null;
  radiusCallingStationId?: string | null;
  snmpOid?: string | null;
  snmpVersion?: ('1' | '2c') | null;
  snmpCommunity?: string | null;
  smtpSecurity?: ('opportunistic' | 'starttls' | 'secure' | 'nostarttls') | null;
  sshUsername?: string | null;
  sshAuthMethod?: ('password' | 'privateKey') | null;
  sshPassword?: string | null;
  sshPrivateKey?: string | null;
  sshPassphrase?: string | null;
  sftpPath?: string | null;
  rabbitmqNodes?: string[] | null;
  rabbitmqUsername?: string | null;
  rabbitmqPassword?: string | null;
  wsSubprotocol?: string | null;
  wsIgnoreSecWebsocketAcceptHeader?: boolean | null;
  game?: string | null;
  gamedigGivenPortOnly?: boolean | null;
  remoteBrowser?: string | null;
  status?: {
    lastStatus?: ('up' | 'down' | 'pending' | 'maintenance' | 'degraded') | null;
    lastCheckAt?: string | null;
    lastPing?: number | null;
    lastMsg?: string | null;
    retries?: number | null;
    downCount?: number | null;
    settledStatus?: ('up' | 'down' | 'pending' | 'maintenance' | 'degraded') | null;
    recoveries?: number | null;
    lastPushAt?: string | null;
    lastPushStatus?: ('up' | 'down') | null;
    pushRuns?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  organization: number | Organization;
  name: string;
  color: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: number;
  organization: number | Organization;
  name: string;
  type: string;
  config:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  events?:
    ('down' | 'up' | 'degraded' | 'reminder' | 'certificate' | 'maintenance' | 'acknowledged' | 'resolved')[] | null;
  isDefault?: boolean | null;
  applyExisting?: boolean | null;
  active?: boolean | null;
  lastSentAt?: string | null;
  lastError?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: number;
  organization: number | Organization;
  name: string;
  slug: string;
  labels?:
    | {
        key: string;
        value?: string | null;
        id?: string | null;
      }[]
    | null;
  tokenHash: string;
  tokenPrefix: string;
  tokenRotatedAt?: string | null;
  status: 'unknown' | 'online' | 'offline';
  statusChangedAt?: string | null;
  lastSeenAt?: string | null;
  agent?: {
    version?: string | null;
    hostname?: string | null;
    platform?: string | null;
  };
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "proxies".
 */
export interface MonitorProxy {
  id: number;
  organization: number | Organization;
  protocol: 'http' | 'https' | 'socks' | 'socks5' | 'socks5h' | 'socks4';
  host: string;
  port: number;
  auth?: boolean | null;
  username?: string | null;
  password?: string | null;
  active?: boolean | null;
  default?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "docker-hosts".
 */
export interface DockerHost {
  id: number;
  organization: number | Organization;
  name: string;
  connectionType: 'socket' | 'tcp';
  socketPath?: string | null;
  url?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notification-sent-history".
 */
export interface NotificationSentHistory {
  id: number;
  organization?: (number | null) | Organization;
  monitor: number | Monitor;
  type: 'certificate' | 'domain';
  days: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "heartbeats".
 */
export interface Heartbeat {
  id: number;
  monitor: number | Monitor;
  organization?: (number | null) | Organization;
  location?: (number | null) | Location;
  status: 'up' | 'down' | 'pending' | 'maintenance' | 'degraded';
  msg?: string | null;
  ping?: number | null;
  duration?: number | null;
  important?: boolean | null;
  trigger?: 'manual' | null;
  assertions?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  timing?: {
    dns?: number | null;
    connect?: number | null;
    tls?: number | null;
    ttfb?: number | null;
    transfer?: number | null;
  };
  probes?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  retries?: number | null;
  downCount?: number | null;
  time: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "monitor-incidents".
 */
export interface MonitorIncident {
  id: number;
  organization: number | Organization;
  monitor: number | Monitor;
  status: 'open' | 'acknowledged' | 'resolved';
  openKey?: string | null;
  cause?: string | null;
  startedAt: string;
  acknowledgedAt?: string | null;
  resolvedAt?: string | null;
  acknowledgedBy?: (number | null) | User;
  acknowledgedVia?: ('dashboard' | 'api' | 'link') | null;
  resolvedBy?: (number | null) | User;
  autoResolved?: boolean | null;
  remindersSent?: number | null;
  lastReminderAt?: string | null;
  statusPageIncident?: (number | null) | Incident;
  timeline?:
    | {
        type: 'opened' | 'maintenance' | 'acknowledged' | 'resolved' | 'published';
        at: string;
        by?: (number | null) | User;
        via?: ('dashboard' | 'api' | 'link') | null;
        message?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "incidents".
 */
export interface Incident {
  id: number;
  organization: number | Organization;
  statusPage: number | StatusPage;
  title: string;
  publicId?: string | null;
  status?: ('investigating' | 'identified' | 'monitoring' | 'resolved') | null;
  impact?: ('operational' | 'degraded_performance' | 'partial_outage' | 'major_outage') | null;
  updates?:
    | {
        status: 'investigating' | 'identified' | 'monitoring' | 'resolved';
        postedAt: string;
        editedAt?: string | null;
        message?: string | null;
        components?:
          | {
              component: string;
              impact: 'operational' | 'degraded_performance' | 'partial_outage' | 'major_outage';
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  affectedComponents?:
    | {
        component: string;
        impact: 'operational' | 'degraded_performance' | 'partial_outage' | 'major_outage';
        id?: string | null;
      }[]
    | null;
  pinned?: boolean | null;
  active?: boolean | null;
  resolvedAt?: string | null;
  content?: string | null;
  style?: ('info' | 'warning' | 'danger' | 'primary') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "status-pages".
 */
export interface StatusPage {
  id: number;
  organization: number | Organization;
  title: string;
  slug: string;
  description?: string | null;
  logo?: (number | null) | Media;
  homepageUrl?: string | null;
  contactUrl?: string | null;
  theme?: ('auto' | 'light' | 'dark') | null;
  themePreset?: string | null;
  themeOverrides?: {
    light?: {
      background?: string;
      foreground?: string;
      card?: string;
      primary?: string;
      primaryForeground?: string;
      muted?: string;
      mutedForeground?: string;
      border?: string;
      success?: string;
      warning?: string;
      info?: string;
      destructive?: string;
      chart1?: string;
      chart2?: string;
      chart3?: string;
      chart4?: string;
      chart5?: string;
    };
    dark?: {
      background?: string;
      foreground?: string;
      card?: string;
      primary?: string;
      primaryForeground?: string;
      muted?: string;
      mutedForeground?: string;
      border?: string;
      success?: string;
      warning?: string;
      info?: string;
      destructive?: string;
      chart1?: string;
      chart2?: string;
      chart3?: string;
      chart4?: string;
      chart5?: string;
    };
    radius?: string;
  } | null;
  bannerText?: string | null;
  logoDark?: (number | null) | Media;
  favicon?: (number | null) | Media;
  language?: ('auto' | 'en') | null;
  published?: boolean | null;
  access?: ('public' | 'password' | 'email-domain' | 'ip-allowlist') | null;
  password?: string | null;
  passwordHash?: string | null;
  allowedEmailDomains?:
    | {
        domain: string;
        id?: string | null;
      }[]
    | null;
  allowedIpRanges?:
    | {
        cidr: string;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  searchEngineIndex?: boolean | null;
  showTags?: boolean | null;
  showCertificateExpiry?: boolean | null;
  showPoweredBy?: boolean | null;
  showValues?: boolean | null;
  autoRefreshInterval?: number | null;
  maintenanceVisibilityHours?: number | null;
  pastIncidentsDays?: number | null;
  footerText?: string | null;
  customCSS?: string | null;
  googleAnalyticsId?: string | null;
  subscriptions?: {
    enabled?: boolean | null;
    deliveryMode?: ('review' | 'auto') | null;
    channels?: ('email' | 'sms' | 'webhook' | 'slack')[] | null;
    smsChannel?: (number | null) | Notification;
    smsMaxSegments?: number | null;
    smsTemplates?: {
      incidentOpened?: string | null;
      incidentUpdated?: string | null;
      maintenanceScheduled?: string | null;
      maintenanceUpdated?: string | null;
    };
  };
  domains?:
    | {
        hostname: string;
        id?: string | null;
      }[]
    | null;
  groups?:
    | {
        name: string;
        defaultOpen?: boolean | null;
        monitors?:
          | {
              type?: ('monitor' | 'static') | null;
              monitor?: (number | null) | Monitor;
              name?: string | null;
              description?: string | null;
              showValues?: boolean | null;
              sendUrl?: boolean | null;
              customUrl?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "push-events".
 */
export interface PushEvent {
  id: number;
  monitor: number | Monitor;
  organization?: (number | null) | Organization;
  kind: 'success' | 'fail' | 'start' | 'log';
  source?: ('http' | 'email') | null;
  msg?: string | null;
  body?: string | null;
  bodyTruncated?: boolean | null;
  rid?: string | null;
  exitCode?: number | null;
  duration?: number | null;
  method?: string | null;
  time: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stat-minutely".
 */
export interface StatMinutely {
  id: number;
  monitor: number | Monitor;
  organization: number | Organization;
  timestamp: number;
  up: number;
  down: number;
  ping?: number | null;
  pingMin?: number | null;
  pingMax?: number | null;
  extras?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stat-hourly".
 */
export interface StatHourly {
  id: number;
  monitor: number | Monitor;
  organization: number | Organization;
  timestamp: number;
  up: number;
  down: number;
  ping?: number | null;
  pingMin?: number | null;
  pingMax?: number | null;
  extras?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stat-daily".
 */
export interface StatDaily {
  id: number;
  monitor: number | Monitor;
  organization: number | Organization;
  timestamp: number;
  up: number;
  down: number;
  ping?: number | null;
  pingMin?: number | null;
  pingMax?: number | null;
  extras?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "status-page-viewers".
 */
export interface StatusPageViewer {
  id: number;
  organization: number | Organization;
  page: number | StatusPage;
  email: string;
  status: 'active' | 'revoked';
  lastSeenAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "status-page-subscribers".
 */
export interface StatusPageSubscriber {
  id: number;
  organization: number | Organization;
  statusPage: number | StatusPage;
  channel: 'email' | 'sms' | 'webhook' | 'slack';
  target: string;
  components?: string[] | null;
  source?: ('self_signup' | 'added_by_owner' | 'import') | null;
  confirmedAt?: string | null;
  locale?: 'en' | null;
  token?: string | null;
  secret?: string | null;
  headers?:
    | {
        name: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  verification?: {
    codeHash?: string | null;
    expiresAt?: string | null;
    attempts?: number | null;
    sentAt?: string | null;
  };
  lastDeliveredAt?: string | null;
  lastError?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriber-notifications".
 */
export interface SubscriberNotification {
  id: number;
  organization: number | Organization;
  statusPage: number | StatusPage;
  dedupeKey: string;
  event:
    | 'incident_opened'
    | 'incident_updated'
    | 'incident_resolved'
    | 'maintenance_scheduled'
    | 'maintenance_reminder'
    | 'maintenance_started'
    | 'maintenance_updated'
    | 'maintenance_completed'
    | 'maintenance_cancelled';
  state: 'pending_review' | 'sending' | 'sent' | 'partially_failed' | 'failed' | 'discarded';
  title: string;
  status?: string | null;
  message?: string | null;
  window?: {
    start?: string | null;
    end?: string | null;
    reminderMinutes?: number | null;
  };
  components?: string[] | null;
  incident?: (number | null) | Incident;
  incidentUpdateId?: string | null;
  maintenance?: (number | null) | Maintenance;
  occurrence?: (number | null) | MaintenanceOccurrence;
  eventPublicId?: string | null;
  occurredAt: string;
  channels?: ('email' | 'sms' | 'webhook' | 'slack')[] | null;
  recipientCount?: number | null;
  sendingStartedAt?: string | null;
  completedAt?: string | null;
  approvedBy?: (number | null) | User;
  approvedAt?: string | null;
  discardedBy?: (number | null) | User;
  discardedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "maintenance".
 */
export interface Maintenance {
  id: number;
  organization: number | Organization;
  title: string;
  description?: string | null;
  strategy: 'manual' | 'single' | 'recurring-interval' | 'recurring-weekday' | 'recurring-day-of-month' | 'cron';
  timezone?: string | null;
  active?: boolean | null;
  status?: ('inactive' | 'scheduled' | 'under-maintenance' | 'ended' | 'unknown') | null;
  dateRange?: {
    start?: string | null;
    end?: string | null;
  };
  timeRange?: {
    start?: string | null;
    end?: string | null;
  };
  intervalDay?: number | null;
  weekdays?: ('1' | '2' | '3' | '4' | '5' | '6' | '0')[] | null;
  daysOfMonth?:
    | (
        | '1'
        | '2'
        | '3'
        | '4'
        | '5'
        | '6'
        | '7'
        | '8'
        | '9'
        | '10'
        | '11'
        | '12'
        | '13'
        | '14'
        | '15'
        | '16'
        | '17'
        | '18'
        | '19'
        | '20'
        | '21'
        | '22'
        | '23'
        | '24'
        | '25'
        | '26'
        | '27'
        | '28'
        | '29'
        | '30'
        | '31'
        | 'lastDay1'
        | 'lastDay2'
        | 'lastDay3'
        | 'lastDay4'
      )[]
    | null;
  cron?: string | null;
  duration?: number | null;
  autoStart?: boolean | null;
  autoComplete?: boolean | null;
  reminders?: ('15' | '30' | '60' | '120' | '360' | '720' | '1440' | '2880' | '10080')[] | null;
  monitors?: (number | Monitor)[] | null;
  statusPages?: (number | StatusPage)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "maintenance-occurrences".
 */
export interface MaintenanceOccurrence {
  id: number;
  organization: number | Organization;
  maintenance: number | Maintenance;
  publicId?: string | null;
  start: string;
  end?: string | null;
  state: 'scheduled' | 'in-progress' | 'verifying' | 'completed' | 'cancelled';
  startedAt?: string | null;
  completedAt?: string | null;
  cancelledAt?: string | null;
  remindersSent?: ('15' | '30' | '60' | '120' | '360' | '720' | '1440' | '2880' | '10080')[] | null;
  updates?:
    | {
        status: 'scheduled' | 'in-progress' | 'verifying' | 'completed' | 'cancelled';
        postedAt: string;
        message?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriber-deliveries".
 */
export interface SubscriberDelivery {
  id: number;
  organization: number | Organization;
  notification: number | SubscriberNotification;
  subscriber: number | StatusPageSubscriber;
  channel: 'email' | 'sms' | 'webhook' | 'slack';
  state: 'queued' | 'retrying' | 'sent' | 'failed' | 'skipped';
  attempts?: number | null;
  error?: string | null;
  sentAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "templates".
 */
export interface Template {
  id: number;
  organization: number | Organization;
  name: string;
  kind: 'incident' | 'incident-update' | 'maintenance' | 'maintenance-update';
  title?: string | null;
  body?: string | null;
  status?: ('investigating' | 'identified' | 'monitoring' | 'resolved') | null;
  impact?: ('operational' | 'degraded_performance' | 'partial_outage' | 'major_outage') | null;
  duration?: number | null;
  statusPage?: (number | null) | StatusPage;
  components?:
    | {
        component: string;
        impact: 'operational' | 'degraded_performance' | 'partial_outage' | 'major_outage';
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "api-keys".
 */
export interface ApiKey {
  id: number;
  organization: number | Organization;
  name: string;
  keyHash: string;
  prefix: string;
  scope: 'read' | 'write';
  active?: boolean | null;
  expiresAt?: string | null;
  lastUsedAt?: string | null;
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: number;
  action: string;
  actorType?: ('user' | 'apiKey' | 'mcp' | 'system') | null;
  actor?: (number | null) | User;
  actorRef?: string | null;
  actorLabel?: string | null;
  organization?: (number | null) | Organization;
  target?: string | null;
  entityType?: string | null;
  entityId?: string | null;
  entityLabel?: string | null;
  changedFields?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  before?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  after?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  ip?: string | null;
  userAgent?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "webhook-endpoints".
 */
export interface WebhookEndpoint {
  id: number;
  organization: number | Organization;
  url: string;
  description?: string | null;
  events:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  active?: boolean | null;
  secret?: string | null;
  previousSecret?: string | null;
  previousSecretExpiresAt?: string | null;
  consecutiveFailures?: number | null;
  disabledReason?: 'failures' | null;
  disabledAt?: string | null;
  lastDeliveryAt?: string | null;
  lastDeliveryState?: ('succeeded' | 'failed') | null;
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "webhook-deliveries".
 */
export interface WebhookDelivery {
  id: number;
  organization: number | Organization;
  endpoint: number | WebhookEndpoint;
  eventId: string;
  eventType: string;
  trigger: 'event' | 'redelivery' | 'test';
  state: 'pending' | 'retrying' | 'succeeded' | 'failed' | 'cancelled';
  attempts?: number | null;
  body:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  requestHeaders?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  responseStatus?: number | null;
  responseHeaders?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  responseBody?: string | null;
  durationMs?: number | null;
  error?: string | null;
  deliveredAt?: string | null;
  redeliveryOf?: (number | null) | WebhookDelivery;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'auth-accounts';
        value: number | AuthAccount;
      } | null)
    | ({
        relationTo: 'organizations';
        value: number | Organization;
      } | null)
    | ({
        relationTo: 'sso-connections';
        value: number | SsoConnection;
      } | null)
    | ({
        relationTo: 'sso-domains';
        value: number | SsoDomain;
      } | null)
    | ({
        relationTo: 'invitations';
        value: number | Invitation;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'monitors';
        value: number | Monitor;
      } | null)
    | ({
        relationTo: 'notifications';
        value: number | Notification;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'proxies';
        value: number | MonitorProxy;
      } | null)
    | ({
        relationTo: 'docker-hosts';
        value: number | DockerHost;
      } | null)
    | ({
        relationTo: 'locations';
        value: number | Location;
      } | null)
    | ({
        relationTo: 'notification-sent-history';
        value: number | NotificationSentHistory;
      } | null)
    | ({
        relationTo: 'heartbeats';
        value: number | Heartbeat;
      } | null)
    | ({
        relationTo: 'monitor-incidents';
        value: number | MonitorIncident;
      } | null)
    | ({
        relationTo: 'push-events';
        value: number | PushEvent;
      } | null)
    | ({
        relationTo: 'stat-minutely';
        value: number | StatMinutely;
      } | null)
    | ({
        relationTo: 'stat-hourly';
        value: number | StatHourly;
      } | null)
    | ({
        relationTo: 'stat-daily';
        value: number | StatDaily;
      } | null)
    | ({
        relationTo: 'status-pages';
        value: number | StatusPage;
      } | null)
    | ({
        relationTo: 'status-page-viewers';
        value: number | StatusPageViewer;
      } | null)
    | ({
        relationTo: 'incidents';
        value: number | Incident;
      } | null)
    | ({
        relationTo: 'status-page-subscribers';
        value: number | StatusPageSubscriber;
      } | null)
    | ({
        relationTo: 'subscriber-notifications';
        value: number | SubscriberNotification;
      } | null)
    | ({
        relationTo: 'subscriber-deliveries';
        value: number | SubscriberDelivery;
      } | null)
    | ({
        relationTo: 'maintenance';
        value: number | Maintenance;
      } | null)
    | ({
        relationTo: 'maintenance-occurrences';
        value: number | MaintenanceOccurrence;
      } | null)
    | ({
        relationTo: 'templates';
        value: number | Template;
      } | null)
    | ({
        relationTo: 'api-keys';
        value: number | ApiKey;
      } | null)
    | ({
        relationTo: 'audit-logs';
        value: number | AuditLog;
      } | null)
    | ({
        relationTo: 'webhook-endpoints';
        value: number | WebhookEndpoint;
      } | null)
    | ({
        relationTo: 'webhook-deliveries';
        value: number | WebhookDelivery;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  avatar?: T;
  superadmin?: T;
  authProvider?: T;
  oidcIssuer?: T;
  oidcSubject?: T;
  theme?: T;
  language?: T;
  twoFactorEnabled?: T;
  twoFactorVerifiedAt?: T;
  twoFactorSecret?: T;
  twoFactorPendingSecret?: T;
  twoFactorBackupCodes?: T;
  twoFactorLastUsedStep?: T;
  organizations?:
    | T
    | {
        organization?: T;
        role?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth-accounts_select".
 */
export interface AuthAccountsSelect<T extends boolean = true> {
  user?: T;
  provider?: T;
  providerAccountId?: T;
  email?: T;
  name?: T;
  lastLoginAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizations_select".
 */
export interface OrganizationsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  logo?: T;
  plan?: T;
  subscriptionStatus?: T;
  stripeCustomerId?: T;
  stripeSubscriptionId?: T;
  inviteLinkToken?: T;
  inviteLinkRole?: T;
  permissionOverrides?: T;
  enforceSso?: T;
  settings?:
    | T
    | {
        timezone?: T;
        weekStart?: T;
        language?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sso-connections_select".
 */
export interface SsoConnectionsSelect<T extends boolean = true> {
  organization?: T;
  name?: T;
  slug?: T;
  type?: T;
  enabled?: T;
  issuerUrl?: T;
  clientId?: T;
  clientSecret?: T;
  scopes?: T;
  idpEntryPoint?: T;
  idpEntityId?: T;
  idpCert?: T;
  wantAssertionsSigned?: T;
  allowIdpInitiated?: T;
  autoProvision?: T;
  defaultRole?: T;
  groupClaim?: T;
  allowedGroups?: T;
  groupRoles?:
    | T
    | {
        group?: T;
        role?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sso-domains_select".
 */
export interface SsoDomainsSelect<T extends boolean = true> {
  organization?: T;
  domain?: T;
  verificationToken?: T;
  verifiedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invitations_select".
 */
export interface InvitationsSelect<T extends boolean = true> {
  organization?: T;
  email?: T;
  role?: T;
  token?: T;
  status?: T;
  expiresAt?: T;
  invitedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "monitors_select".
 */
export interface MonitorsSelect<T extends boolean = true> {
  organization?: T;
  name?: T;
  type?: T;
  active?: T;
  parent?: T;
  key?: T;
  publicName?: T;
  description?: T;
  tags?:
    | T
    | {
        tag?: T;
        value?: T;
        id?: T;
      };
  notifications?: T;
  locations?: T;
  weight?: T;
  url?: T;
  proxy?: T;
  dockerHost?: T;
  dockerContainer?: T;
  hostname?: T;
  port?: T;
  interval?: T;
  retryInterval?: T;
  maxRetries?: T;
  resendInterval?: T;
  timeout?: T;
  degradedAfter?: T;
  successThreshold?: T;
  reminderBackoff?: T;
  maxReminders?: T;
  upsideDown?: T;
  method?: T;
  httpBodyEncoding?: T;
  maxRedirects?: T;
  body?: T;
  headers?: T;
  acceptedStatusCodes?: T;
  ignoreTls?: T;
  expiryNotification?: T;
  domainExpiryNotification?: T;
  certInfo?: T;
  domainExpiry?: T;
  keyword?: T;
  invertKeyword?: T;
  jsonPath?: T;
  jsonPathOperator?: T;
  expectedValue?: T;
  assertions?:
    | T
    | {
        kind?: T;
        target?: T;
        comparator?: T;
        value?: T;
        id?: T;
      };
  authMethod?: T;
  basicAuthUser?: T;
  basicAuthPass?: T;
  authDomain?: T;
  authWorkstation?: T;
  bearerToken?: T;
  oauthTokenUrl?: T;
  oauthClientId?: T;
  oauthClientSecret?: T;
  oauthScopes?: T;
  oauthAuthMethod?: T;
  tlsCert?: T;
  tlsKey?: T;
  tlsCa?: T;
  dnsResolveServer?: T;
  dnsResolveType?: T;
  globalpingMeasurement?: T;
  globalpingProtocol?: T;
  globalpingIpVersion?: T;
  globalpingLocations?: T;
  globalpingProbes?: T;
  globalpingSuccessRule?: T;
  globalpingMinSuccess?: T;
  globalpingPackets?: T;
  pushToken?: T;
  pushSchedule?: T;
  pushCron?: T;
  pushTimezone?: T;
  pushGrace?: T;
  pushMaxDuration?: T;
  manualStatus?: T;
  databaseConnectionString?: T;
  databaseQuery?: T;
  mqttTopic?: T;
  mqttUsername?: T;
  mqttPassword?: T;
  mqttCheckType?: T;
  mqttSuccessMessage?: T;
  kafkaProducerBrokers?: T;
  kafkaProducerTopic?: T;
  kafkaProducerMessage?: T;
  kafkaProducerSsl?: T;
  kafkaProducerAllowAutoTopicCreation?: T;
  kafkaProducerSaslOptions?: T;
  grpcUrl?: T;
  grpcServiceName?: T;
  grpcMethod?: T;
  grpcEnableTls?: T;
  grpcProtobuf?: T;
  grpcBody?: T;
  grpcMetadata?: T;
  radiusUsername?: T;
  radiusPassword?: T;
  radiusSecret?: T;
  radiusCalledStationId?: T;
  radiusCallingStationId?: T;
  snmpOid?: T;
  snmpVersion?: T;
  snmpCommunity?: T;
  smtpSecurity?: T;
  sshUsername?: T;
  sshAuthMethod?: T;
  sshPassword?: T;
  sshPrivateKey?: T;
  sshPassphrase?: T;
  sftpPath?: T;
  rabbitmqNodes?: T;
  rabbitmqUsername?: T;
  rabbitmqPassword?: T;
  wsSubprotocol?: T;
  wsIgnoreSecWebsocketAcceptHeader?: T;
  game?: T;
  gamedigGivenPortOnly?: T;
  remoteBrowser?: T;
  status?:
    | T
    | {
        lastStatus?: T;
        lastCheckAt?: T;
        lastPing?: T;
        lastMsg?: T;
        retries?: T;
        downCount?: T;
        settledStatus?: T;
        recoveries?: T;
        lastPushAt?: T;
        lastPushStatus?: T;
        pushRuns?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  organization?: T;
  name?: T;
  type?: T;
  config?: T;
  events?: T;
  isDefault?: T;
  applyExisting?: T;
  active?: T;
  lastSentAt?: T;
  lastError?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  organization?: T;
  name?: T;
  color?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "proxies_select".
 */
export interface ProxiesSelect<T extends boolean = true> {
  organization?: T;
  protocol?: T;
  host?: T;
  port?: T;
  auth?: T;
  username?: T;
  password?: T;
  active?: T;
  default?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "docker-hosts_select".
 */
export interface DockerHostsSelect<T extends boolean = true> {
  organization?: T;
  name?: T;
  connectionType?: T;
  socketPath?: T;
  url?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations_select".
 */
export interface LocationsSelect<T extends boolean = true> {
  organization?: T;
  name?: T;
  slug?: T;
  labels?:
    | T
    | {
        key?: T;
        value?: T;
        id?: T;
      };
  tokenHash?: T;
  tokenPrefix?: T;
  tokenRotatedAt?: T;
  status?: T;
  statusChangedAt?: T;
  lastSeenAt?: T;
  agent?:
    | T
    | {
        version?: T;
        hostname?: T;
        platform?: T;
      };
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notification-sent-history_select".
 */
export interface NotificationSentHistorySelect<T extends boolean = true> {
  organization?: T;
  monitor?: T;
  type?: T;
  days?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "heartbeats_select".
 */
export interface HeartbeatsSelect<T extends boolean = true> {
  monitor?: T;
  organization?: T;
  location?: T;
  status?: T;
  msg?: T;
  ping?: T;
  duration?: T;
  important?: T;
  trigger?: T;
  assertions?: T;
  timing?:
    | T
    | {
        dns?: T;
        connect?: T;
        tls?: T;
        ttfb?: T;
        transfer?: T;
      };
  probes?: T;
  retries?: T;
  downCount?: T;
  time?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "monitor-incidents_select".
 */
export interface MonitorIncidentsSelect<T extends boolean = true> {
  organization?: T;
  monitor?: T;
  status?: T;
  openKey?: T;
  cause?: T;
  startedAt?: T;
  acknowledgedAt?: T;
  resolvedAt?: T;
  acknowledgedBy?: T;
  acknowledgedVia?: T;
  resolvedBy?: T;
  autoResolved?: T;
  remindersSent?: T;
  lastReminderAt?: T;
  statusPageIncident?: T;
  timeline?:
    | T
    | {
        type?: T;
        at?: T;
        by?: T;
        via?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "push-events_select".
 */
export interface PushEventsSelect<T extends boolean = true> {
  monitor?: T;
  organization?: T;
  kind?: T;
  source?: T;
  msg?: T;
  body?: T;
  bodyTruncated?: T;
  rid?: T;
  exitCode?: T;
  duration?: T;
  method?: T;
  time?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stat-minutely_select".
 */
export interface StatMinutelySelect<T extends boolean = true> {
  monitor?: T;
  organization?: T;
  timestamp?: T;
  up?: T;
  down?: T;
  ping?: T;
  pingMin?: T;
  pingMax?: T;
  extras?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stat-hourly_select".
 */
export interface StatHourlySelect<T extends boolean = true> {
  monitor?: T;
  organization?: T;
  timestamp?: T;
  up?: T;
  down?: T;
  ping?: T;
  pingMin?: T;
  pingMax?: T;
  extras?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stat-daily_select".
 */
export interface StatDailySelect<T extends boolean = true> {
  monitor?: T;
  organization?: T;
  timestamp?: T;
  up?: T;
  down?: T;
  ping?: T;
  pingMin?: T;
  pingMax?: T;
  extras?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "status-pages_select".
 */
export interface StatusPagesSelect<T extends boolean = true> {
  organization?: T;
  title?: T;
  slug?: T;
  description?: T;
  logo?: T;
  homepageUrl?: T;
  contactUrl?: T;
  theme?: T;
  themePreset?: T;
  themeOverrides?: T;
  bannerText?: T;
  logoDark?: T;
  favicon?: T;
  language?: T;
  published?: T;
  access?: T;
  password?: T;
  passwordHash?: T;
  allowedEmailDomains?:
    | T
    | {
        domain?: T;
        id?: T;
      };
  allowedIpRanges?:
    | T
    | {
        cidr?: T;
        label?: T;
        id?: T;
      };
  searchEngineIndex?: T;
  showTags?: T;
  showCertificateExpiry?: T;
  showPoweredBy?: T;
  showValues?: T;
  autoRefreshInterval?: T;
  maintenanceVisibilityHours?: T;
  pastIncidentsDays?: T;
  footerText?: T;
  customCSS?: T;
  googleAnalyticsId?: T;
  subscriptions?:
    | T
    | {
        enabled?: T;
        deliveryMode?: T;
        channels?: T;
        smsChannel?: T;
        smsMaxSegments?: T;
        smsTemplates?:
          | T
          | {
              incidentOpened?: T;
              incidentUpdated?: T;
              maintenanceScheduled?: T;
              maintenanceUpdated?: T;
            };
      };
  domains?:
    | T
    | {
        hostname?: T;
        id?: T;
      };
  groups?:
    | T
    | {
        name?: T;
        defaultOpen?: T;
        monitors?:
          | T
          | {
              type?: T;
              monitor?: T;
              name?: T;
              description?: T;
              showValues?: T;
              sendUrl?: T;
              customUrl?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "status-page-viewers_select".
 */
export interface StatusPageViewersSelect<T extends boolean = true> {
  organization?: T;
  page?: T;
  email?: T;
  status?: T;
  lastSeenAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "incidents_select".
 */
export interface IncidentsSelect<T extends boolean = true> {
  organization?: T;
  statusPage?: T;
  title?: T;
  publicId?: T;
  status?: T;
  impact?: T;
  updates?:
    | T
    | {
        status?: T;
        postedAt?: T;
        editedAt?: T;
        message?: T;
        components?:
          | T
          | {
              component?: T;
              impact?: T;
              id?: T;
            };
        id?: T;
      };
  affectedComponents?:
    | T
    | {
        component?: T;
        impact?: T;
        id?: T;
      };
  pinned?: T;
  active?: T;
  resolvedAt?: T;
  content?: T;
  style?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "status-page-subscribers_select".
 */
export interface StatusPageSubscribersSelect<T extends boolean = true> {
  organization?: T;
  statusPage?: T;
  channel?: T;
  target?: T;
  components?: T;
  source?: T;
  confirmedAt?: T;
  locale?: T;
  token?: T;
  secret?: T;
  headers?:
    | T
    | {
        name?: T;
        value?: T;
        id?: T;
      };
  verification?:
    | T
    | {
        codeHash?: T;
        expiresAt?: T;
        attempts?: T;
        sentAt?: T;
      };
  lastDeliveredAt?: T;
  lastError?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriber-notifications_select".
 */
export interface SubscriberNotificationsSelect<T extends boolean = true> {
  organization?: T;
  statusPage?: T;
  dedupeKey?: T;
  event?: T;
  state?: T;
  title?: T;
  status?: T;
  message?: T;
  window?:
    | T
    | {
        start?: T;
        end?: T;
        reminderMinutes?: T;
      };
  components?: T;
  incident?: T;
  incidentUpdateId?: T;
  maintenance?: T;
  occurrence?: T;
  eventPublicId?: T;
  occurredAt?: T;
  channels?: T;
  recipientCount?: T;
  sendingStartedAt?: T;
  completedAt?: T;
  approvedBy?: T;
  approvedAt?: T;
  discardedBy?: T;
  discardedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriber-deliveries_select".
 */
export interface SubscriberDeliveriesSelect<T extends boolean = true> {
  organization?: T;
  notification?: T;
  subscriber?: T;
  channel?: T;
  state?: T;
  attempts?: T;
  error?: T;
  sentAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "maintenance_select".
 */
export interface MaintenanceSelect<T extends boolean = true> {
  organization?: T;
  title?: T;
  description?: T;
  strategy?: T;
  timezone?: T;
  active?: T;
  status?: T;
  dateRange?:
    | T
    | {
        start?: T;
        end?: T;
      };
  timeRange?:
    | T
    | {
        start?: T;
        end?: T;
      };
  intervalDay?: T;
  weekdays?: T;
  daysOfMonth?: T;
  cron?: T;
  duration?: T;
  autoStart?: T;
  autoComplete?: T;
  reminders?: T;
  monitors?: T;
  statusPages?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "maintenance-occurrences_select".
 */
export interface MaintenanceOccurrencesSelect<T extends boolean = true> {
  organization?: T;
  maintenance?: T;
  publicId?: T;
  start?: T;
  end?: T;
  state?: T;
  startedAt?: T;
  completedAt?: T;
  cancelledAt?: T;
  remindersSent?: T;
  updates?:
    | T
    | {
        status?: T;
        postedAt?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "templates_select".
 */
export interface TemplatesSelect<T extends boolean = true> {
  organization?: T;
  name?: T;
  kind?: T;
  title?: T;
  body?: T;
  status?: T;
  impact?: T;
  duration?: T;
  statusPage?: T;
  components?:
    | T
    | {
        component?: T;
        impact?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "api-keys_select".
 */
export interface ApiKeysSelect<T extends boolean = true> {
  organization?: T;
  name?: T;
  keyHash?: T;
  prefix?: T;
  scope?: T;
  active?: T;
  expiresAt?: T;
  lastUsedAt?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  action?: T;
  actorType?: T;
  actor?: T;
  actorRef?: T;
  actorLabel?: T;
  organization?: T;
  target?: T;
  entityType?: T;
  entityId?: T;
  entityLabel?: T;
  changedFields?: T;
  before?: T;
  after?: T;
  ip?: T;
  userAgent?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "webhook-endpoints_select".
 */
export interface WebhookEndpointsSelect<T extends boolean = true> {
  organization?: T;
  url?: T;
  description?: T;
  events?: T;
  active?: T;
  secret?: T;
  previousSecret?: T;
  previousSecretExpiresAt?: T;
  consecutiveFailures?: T;
  disabledReason?: T;
  disabledAt?: T;
  lastDeliveryAt?: T;
  lastDeliveryState?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "webhook-deliveries_select".
 */
export interface WebhookDeliveriesSelect<T extends boolean = true> {
  organization?: T;
  endpoint?: T;
  eventId?: T;
  eventType?: T;
  trigger?: T;
  state?: T;
  attempts?: T;
  body?: T;
  requestHeaders?: T;
  responseStatus?: T;
  responseHeaders?: T;
  responseBody?: T;
  durationMs?: T;
  error?: T;
  deliveredAt?: T;
  redeliveryOf?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "instance-settings".
 */
export interface InstanceSetting {
  id: number;
  /**
   * Public URL of this instance, used in notifications and status page links. Defaults to NEXT_PUBLIC_SERVER_URL.
   */
  primaryBaseUrl?: string | null;
  /**
   * Allow anyone to create an account. When off, only invited users can register. Defaults to the inverse of DISABLE_SIGNUP.
   */
  allowSignup?: boolean | null;
  /**
   * What visitors of the root URL see.
   */
  entryPage?: ('dashboard' | 'status-page') | null;
  /**
   * Notify this many days before a TLS certificate expires.
   */
  tlsExpiryNotifyDays?: number[] | null;
  /**
   * Notify this many days before a domain registration expires.
   */
  domainExpiryNotifyDays?: number[] | null;
  /**
   * Retention of daily aggregates and important heartbeats, in days (0 disables pruning). Defaults to KEEP_DATA_PERIOD_DAYS.
   */
  keepDataPeriodDays?: number | null;
  /**
   * Trust X-Forwarded-* headers from the reverse proxy when determining client IPs.
   */
  trustProxy?: boolean | null;
  /**
   * Steam Web API key for Steam Game Server monitors.
   */
  steamApiKey?: string | null;
  /**
   * Globalping API token for remote ping/HTTP checks.
   */
  globalpingApiToken?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "instance-settings_select".
 */
export interface InstanceSettingsSelect<T extends boolean = true> {
  primaryBaseUrl?: T;
  allowSignup?: T;
  entryPage?: T;
  tlsExpiryNotifyDays?: T;
  domainExpiryNotifyDays?: T;
  keepDataPeriodDays?: T;
  trustProxy?: T;
  steamApiKey?: T;
  globalpingApiToken?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}